apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nexus-server.fullname" . }}
  labels:
    {{- include "nexus-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nexus-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nexus-server.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      containers:
        - name: nexus-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.server.port }}
              protocol: TCP
          env:
            - name: NEXUS__SERVER__PORT
              value: {{ .Values.server.port | quote }}
            - name: NEXUS__SERVER__HOST
              value: {{ .Values.server.host | quote }}
            - name: NEXUS__CAS__BASE_URL
              value: {{ .Values.cas.baseUrl | quote }}
            - name: NEXUS__CAS__REGION
              value: {{ .Values.cas.region | quote }}
            - name: NEXUS__CAS__DEFAULT_BUCKET
              value: {{ .Values.cas.defaultBucket | quote }}
            - name: NEXUS__DATABASE__MAX_CONNECTIONS
              value: {{ .Values.database.maxConnections | quote }}
            {{- if .Values.ingest.batchItemConcurrency }}
            - name: NEXUS__INGEST__BATCH_ITEM_CONCURRENCY
              value: {{ .Values.ingest.batchItemConcurrency | quote }}
            {{- end }}
            {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          envFrom:
            - secretRef:
                name: {{ include "nexus-server.secretName" . }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
